version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
  frontend:
    depends_on:
      - backend
    build: ./frontend
    environment:
      - POKER_BACKEND_BASE_URL=backend
    ports:
      - 80:80
